---
title: "rvesting-movies"
author: "Silas Bamidele"
date: "2023-08-02"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Harvesting IMDB Movies with RVest

Get movie titles
```{r}
library(dplyr)
library(stringr)
library(rvest)

url <- "https://imdb.com/chart/top"
top_movies <- read_html(url)   #read the supplied url with read_html -- powered by rvest
top_movies %>% 
  html_nodes("ul.ipc-metadata-list li div.cli-children h3") %>%  #pipe top_movies into html_nodes and html_text 
  html_text() -> top_movies

top_movies %>% 
  str_trim() %>%  
  str_split("\n") -> top_movies   #After trimming and splitting it down, you get a LIST

top_movies %>%  #outputs as a list here, so let's unlist
  unlist() -> top_movies  # after unlisting, you then get a vector of characters, with the movie names

#You can drill down into individual characters with top_movies[index] -- where index is the index number
#top_movies[1] -- returns [1] "1. The Shawshank Redemption19942h 22m12A9.3Rate"


  top_movies %>% 
    str_replace("^\\d+\\.\\s*", "") -> top_movies
  
  top_movies %>% 
    as.character() -> top_movies #type casting
  
  top_movies
  
 
```

Get movie years
```{r}
library(dplyr)
library(stringr)
library(rvest)

url <- "https://imdb.com/chart/top"
top_movies <- read_html(url)   #read the supplied url with read_html -- powered by rvest
top_movies %>% 
  html_nodes("ul.ipc-metadata-list li div.cli-title-metadata") %>%  #pipe top_movies into html_nodes and html_text 
  html_text() -> top_years

top_years %>% 
  str_extract("\\d{4}") -> top_years # extracts the year values from the data

top_years %>% 
  as.integer() -> top_years #type casting to integer

```

Get movie ratings
```{r}
library(dplyr)
library(stringr)
library(rvest)

url <- "https://imdb.com/chart/top"
top_movies <- read_html(url)   #read the supplied url with read_html -- powered by rvest
top_movies %>% 
  html_nodes("ul.ipc-metadata-list li .ipc-rating-star--imdb") %>%  #pipe into html_nodes and html_text -- most important here 
  html_text() -> top_ratings  # returns all ratings in char format. Let's change to numeric

top_ratings %>% 
  as.numeric() -> top_ratings #type casting

top_ratings

```

Now let's couple up a DF with the tibble function

```{r}

library(tibble)
library(dplyr)
tibble(
  Movies = top_movies,
  Movie_Years = top_years,
  Ratings = top_ratings
       ) -> imdb_top_250

imdb_top_250 %>% 
  arrange(Movie_Years) -> imdb  #to see the earliest movie made, for example, in the top 250 movies

imdb

```

Writing the tibble to csv
```{r}
# Load the readr package
library(readr)


# Tibble to write
my_tibble <- imdb_top_250

# Define the path where you want to save the CSV file
file_path <- "/home/silas/rvesting-movies/top_250_movies.csv"

#Notice the path includes a file name

# Write the tibble to a CSV file
write_csv(my_tibble, file_path)

```


